
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docreader.serviceAccountName" . }}
  labels:
    {{- include "docreader.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}
